### ISSUE TITLE
Files get put alongside destination directory

### ISSUE THREAD

**Issue by scfonowy** [elliottwilliams/XcodeMove#5]
When a directory is passed as the destination, files will be placed alongside the directory (i.e. in the destination's parent), not in the destination itself.

I am under the impression that it is related to [this commit,](https://github.com/elliottwilliams/XcodeMove/commit/9a273f8e65bdec27760de3de631cf3df35be0a7a) but may be mistaken.

**Comment by elliottwilliams** [comment]
Ohh, yep. Because the dirname of a file is its containing directory, but the dirname of a directory is its parent.

I should really write some unit tests.
